import 'package:flutter/material.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Privacy Policy'),
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildSectionText('Last updated: January 30, 2025'),
            SizedBox(height: 20),

            _buildSectionTitle('Introduction'),
            _buildSectionText(
                'This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and informs You of Your privacy rights and how the law protects You.'),
            _buildSectionText(
                'We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.'),

            SizedBox(height: 20),
            _buildSectionTitle('Interpretation and Definitions'),

            _buildSubSectionTitle('Interpretation'),
            _buildSectionText(
                'The words with initial capital letters have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.'),

            _buildSubSectionTitle('Definitions'),
            _buildSectionText('For the purposes of this Privacy Policy:'),
            _buildBulletText(
                'Account means a unique account created for You to access our Service or parts of our Service.'),
            _buildBulletText(
                'Affiliate means an entity that controls, is controlled by, or is under common control with a party.'),
            _buildBulletText(
                'Application refers to GuardX, the software program provided by the Company.'),
            _buildBulletText(
                'Company (referred to as "the Company," "We," "Us," or "Our" in this Agreement) refers to GuardX.'),
            _buildBulletText('Country refers to: Uttar Pradesh, India.'),
            _buildBulletText(
                'Device means any device that can access the Service such as a computer, cellphone, or digital tablet.'),
            _buildBulletText(
                'Personal Data means any information that relates to an identified or identifiable individual.'),
            _buildBulletText('Service refers to the Application.'),
            _buildBulletText(
                'Service Provider means any natural or legal person who processes the data on behalf of the Company.'),
            _buildBulletText(
                'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.'),
            _buildBulletText(
                'You means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service.'),

            SizedBox(height: 20),
            _buildSectionTitle('Collecting and Using Your Personal Data'),

            _buildSubSectionTitle('Types of Data Collected'),
            _buildSubSectionTitle('1. Personal Data'),
            _buildSectionText(
                'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:'),
            _buildBulletText('Email address'),
            _buildBulletText('Password (encrypted)'),
            _buildBulletText('Name (optional)'),

            _buildSubSectionTitle('2. Sensitive Data'),
            _buildSectionText(
                'The core functionality of the GuardX Application involves securely storing sensitive data. This may include:'),
            _buildBulletText('Social media and email account credentials'),
            _buildBulletText(
                'Bank card information, such as credit card, debit card, or ATM details'),
            _buildBulletText('Custom passwords for websites or applications'),
            _buildSectionText(
                '**Note:** We use strong encryption methods to securely store sensitive information. The data is only accessible through user authentication.'),

            _buildSubSectionTitle('3. Usage Data'),
            _buildSectionText(
                'Usage Data is collected automatically when using the Service. It may include information such as:'),
            _buildBulletText(
                "Your Device’s Internet Protocol address (IP address)"),
            _buildBulletText('Browser type and version'),
            _buildBulletText(
                'Pages visited, time and date of visit, and time spent on those pages'),
            _buildBulletText('Diagnostic data, such as errors and crashes'),

            _buildSubSectionTitle('4. Device Data'),
            _buildSectionText(
                'When You access the Service by or through a mobile device, We may collect automatically:'),
            _buildBulletText('The type of mobile device You use'),
            _buildBulletText('Your mobile device’s unique ID and IP address'),
            _buildBulletText(
                'Operating system and mobile Internet browser information'),

            SizedBox(height: 20),
            _buildSectionTitle('Use of Your Personal Data'),
            _buildSectionText(
                'We may use Personal Data for the following purposes:'),
            _buildBulletText(
                'To provide and maintain our Service: To ensure smooth user registration, access to sensitive data storage, and secure functionality.'),
            _buildBulletText(
                'To manage Your Account: To give You access to different functionalities within the Service.'),
            _buildBulletText(
                'For secure storage of sensitive information: To enable You to securely store and retrieve saved passwords, card details, and credentials.'),
            _buildBulletText(
                'To contact You: For updates, service notifications, or security alerts.'),
            _buildBulletText(
                'To improve our Service: For troubleshooting, user feedback, and enhancing security.'),
            _buildBulletText(
                'To comply with legal obligations: When necessary to meet regulatory or legal requirements.'),

            SizedBox(height: 20),
            _buildSectionTitle('Sharing Your Personal Data'),
            _buildSectionText(
                'We may share Your personal information in the following situations:'),
            _buildBulletText(
                'With Service Providers: To perform data processing tasks securely.'),
            _buildBulletText(
                'For business transfers: In connection with a merger, sale, or transfer of company assets.'),
            _buildBulletText(
                'With affiliates and business partners: Under strict confidentiality.'),
            _buildBulletText(
                'With Your consent: For any other purpose with Your approval.'),

            // The remaining sections will follow the same pattern...
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.bold,
      ),
    );
  }

  Widget _buildSubSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(top: 10.0),
      child: Text(
        title,
        style: TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Widget _buildSectionText(String text) {
    return Padding(
      padding: const EdgeInsets.only(top: 8.0),
      child: Text(
        text,
        style: TextStyle(fontSize: 16),
      ),
    );
  }

  Widget _buildBulletText(String text) {
    return Padding(
      padding: const EdgeInsets.only(left: 16.0, top: 4.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text("\u2022 ", style: TextStyle(fontSize: 26)),
          SizedBox(width: 6),
          Expanded(
            child: Text(
              text,
              style: TextStyle(fontSize: 16),
            ),
          ),
        ],
      ),
    );
  }
}
