// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKyeJdqoRbd5ThvnRh5lIljV5_ovweVCA',
    appId: '1:984960247129:web:ed8aeeba0649243a09d848',
    messagingSenderId: '984960247129',
    projectId: 'kawach-59de0',
    authDomain: 'kawach-59de0.firebaseapp.com',
    storageBucket: 'kawach-59de0.appspot.com',
    measurementId: 'G-JJF3GEVTNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcqmANTPh85Mo0OXSC9ywuWuBXHg6MI_c',
    appId: '1:984960247129:android:62f845ca75708fed09d848',
    messagingSenderId: '984960247129',
    projectId: 'kawach-59de0',
    storageBucket: 'kawach-59de0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzL5sh4UBAze_zNBNmm8ZeOZzWwTLMYHs',
    appId: '1:984960247129:ios:ae0431b08753ee6009d848',
    messagingSenderId: '984960247129',
    projectId: 'kawach-59de0',
    storageBucket: 'kawach-59de0.appspot.com',
    iosBundleId: 'in.crewhub.kawach.kawach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzL5sh4UBAze_zNBNmm8ZeOZzWwTLMYHs',
    appId: '1:984960247129:ios:ae0431b08753ee6009d848',
    messagingSenderId: '984960247129',
    projectId: 'kawach-59de0',
    storageBucket: 'kawach-59de0.appspot.com',
    iosBundleId: 'in.crewhub.kawach.kawach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKyeJdqoRbd5ThvnRh5lIljV5_ovweVCA',
    appId: '1:984960247129:web:b1f45d932a7d782b09d848',
    messagingSenderId: '984960247129',
    projectId: 'kawach-59de0',
    authDomain: 'kawach-59de0.firebaseapp.com',
    storageBucket: 'kawach-59de0.appspot.com',
    measurementId: 'G-MXTHPHQTSY',
  );
}
